export const heroSlides = [
  {
    label: 'Simien Mountains',
    title: 'Trek the Roof of Africa',
    description: 'Journey through dramatic peaks, deep valleys, and encounter rare Gelada baboons in Ethiopia\'s most spectacular national park.',
    image: 'https://i.pinimg.com/1200x/1e/08/53/1e0853201c6e13dbde41a21a76651da2.jpg',
    chips: ['Mountain Trekking', 'Wildlife', 'UNESCO Heritage', 'Camping'],
  },
  {
    label: 'Lalibela',
    title: 'The Eighth Wonder of the World',
    description: 'Explore 11 magnificent rock-hewn churches carved from solid stone, a pilgrimage site and testament to ancient Ethiopian faith.',
    image: 'https://i.pinimg.com/1200x/67/66/e9/6766e9ee08c75fd62a0ed7a64d3e94e7.jpg',
    chips: ['Rock Churches', 'Pilgrimage', 'UNESCO', 'Spiritual Journey'],
  },
  {
    label: 'Danakil Depression',
    title: 'The Hottest Place on Earth',
    description: 'Witness otherworldly landscapes with neon-green acid pools, yellow sulfur fields, and an active lava lake at Erta Ale volcano.',
    image: 'https://i.pinimg.com/1200x/cc/02/48/cc02489d2a5cda830768a437435f3100.jpg',
    chips: ['Volcano Trek', 'Salt Flats', 'Extreme Adventure', 'Photography'],
  },
  {
    label: 'Lake Tana & Blue Nile',
    title: 'Source of the Mighty Nile',
    description: 'Boat across Ethiopia\'s largest lake to ancient island monasteries and witness the majestic "Smoking Water" falls.',
    image: 'https://i.pinimg.com/1200x/3d/f7/a3/3df7a385771f5cc2182413c233928653.jpg',
    chips: ['Boat Tours', 'Monasteries', 'Waterfalls', 'Bird Watching'],
  },
  {
    label: 'Axum',
    title: 'Kingdom of the Queen of Sheba',
    description: 'Discover towering ancient obelisks, royal tombs, and the legendary Ark of the Covenant in Ethiopia\'s oldest city.',
    image: 'https://i.pinimg.com/1200x/83/3a/ba/833aba3c380ab10bc6bc2910889b84d2.jpg',
    chips: ['Ancient Obelisks', 'Archaeology', 'History', 'Royal Tombs'],
  },
  {
    label: 'Harar Jugol',
    title: 'The Walled Living Museum',
    description: 'Wander through 368 winding alleys in the fourth holiest Islamic city, and witness the famous nightly hyena feeding.',
    image: 'https://i.pinimg.com/1200x/29/6c/11/296c11e45718664ee98274afacbe9f96.jpg',
    chips: ['Walled City', 'Islamic Heritage', 'Hyena Men', 'Colorful Markets'],
  },
  {
    label: 'Bale Mountains',
    title: 'Ethiopia\'s Alpine Wonderland',
    description: 'Trek through afro-alpine landscapes, spot the rare Ethiopian wolf, and discover stunning crater lakes.',
    image: 'https://i.pinimg.com/1200x/fc/04/59/fc045970c7abfb3141568fc4da87b600.jpg',
    chips: ['Mountain Trekking', 'Wildlife', 'Endemic Birds', 'Crater Lakes'],
  },
  {
    label: 'Omo Valley',
    title: 'Cradle of Humankind',
    description: 'Meet ancient tribes, witness unique cultural ceremonies, and explore one of the world\'s most fascinating anthropological sites.',
    image: 'https://i.pinimg.com/736x/09/d8/1b/09d81b03191809eef38031b8bd7cc95f.jpg',
    chips: ['Cultural Tours', 'Tribal Encounters', 'Anthropology', 'Photography'],
  },
];

export const authVisuals = [
  {
    label: 'Lalibela',
    title: 'Begin Your Ethiopian Journey',
    description: 'Create your account and start planning adventures through ancient rock churches and breathtaking highlands.',
    snippet: '11 rock-hewn churches await',
    image: 'https://images.unsplash.com/photo-1598808503746-f34c53b9323c?w=1600',
  },
  {
    label: 'Simien Mountains',
    title: 'Your Gateway to Adventure',
    description: 'Sign in to access curated itineraries, book treks, and manage your Ethiopian travel experiences.',
    snippet: 'Trek the Roof of Africa',
    image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01ef0?w=1600',
  },
  {
    label: 'Danakil Depression',
    title: 'Explore the Extraordinary',
    description: 'Login to discover unique landscapes, from colorful hydrothermal fields to active volcanoes.',
    snippet: 'Witness otherworldly beauty',
    image: 'https://images.unsplash.com/photo-1587923623987-c8a9ecc40f3a?w=1600',
  },
  {
    label: 'Lake Tana',
    title: 'Discover Ancient Monasteries',
    description: 'Join our community to explore Ethiopia\'s largest lake and the source of the Blue Nile.',
    snippet: 'Boat to island monasteries',
    image: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=1600',
  },
  {
    label: 'Axum',
    title: 'Walk Through History',
    description: 'Register to explore ancient obelisks, royal tombs, and the legendary Ark of the Covenant.',
    snippet: 'Ancient civilization awaits',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1600',
  },
  {
    label: 'Harar',
    title: 'Experience Living Heritage',
    description: 'Sign up to wander through the walled city and witness the famous hyena feeding ritual.',
    snippet: '368 colorful alleyways',
    image: 'https://images.unsplash.com/photo-1598808503746-f34c53b9323c?w=1600',
  },
];