export const mockDestinations = [
  {
    id: 1,
    name: "Lalibela Rock Churches",
    slug: "lalibela-rock-churches",
    description: "Experience the mystical rock-hewn churches of Lalibela, a UNESCO World Heritage site and one of Ethiopia's holiest cities.",
    city: "Lalibela",
    country: "Ethiopia",
    main_image: "https://images.unsplash.com/photo-1547471080-7cc2caa01ef0?w=800",
    price_per_person: 450,
    discount_price: 399,
    duration: 5,
    difficulty: "moderate",
    max_people: 15,
    rating: 4.8,
    review_count: 124,
    is_featured: true,
  },
  {
    id: 2,
    name: "Simien Mountains Trek",
    slug: "simien-mountains-trek",
    description: "Trek through the breathtaking Simien Mountains National Park, home to endemic wildlife and stunning landscapes.",
    city: "Debark",
    country: "Ethiopia",
    main_image: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800",
    price_per_person: 650,
    discount_price: 599,
    duration: 7,
    difficulty: "hard",
    max_people: 12,
    rating: 4.9,
    review_count: 89,
    is_featured: true,
  },
  {
    id: 3,
    name: "Omo Valley Cultural Tour",
    slug: "omo-valley-cultural-tour",
    description: "Immerse yourself in the rich cultural traditions of the Omo Valley tribes, one of Africa's most fascinating cultural destinations.",
    city: "Jinka",
    country: "Ethiopia",
    main_image: "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800",
    price_per_person: 850,
    discount_price: 799,
    duration: 10,
    difficulty: "moderate",
    max_people: 10,
    rating: 4.7,
    review_count: 156,
    is_featured: true,
  },
  {
    id: 4,
    name: "Danakil Depression Expedition",
    slug: "danakil-depression",
    description: "Journey to one of the hottest and most alien landscapes on Earth - the Danakil Depression with its colorful sulfur springs.",
    city: "Mekele",
    country: "Ethiopia",
    main_image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800",
    price_per_person: 750,
    discount_price: 699,
    duration: 6,
    difficulty: "hard",
    max_people: 8,
    rating: 4.6,
    review_count: 67,
    is_featured: false,
  },
  {
    id: 5,
    name: "Bahir Dar & Lake Tana",
    slug: "bahir-dar-lake-tana",
    description: "Explore the beautiful Lake Tana monasteries and the Blue Nile Falls on this relaxing cultural journey.",
    city: "Bahir Dar",
    country: "Ethiopia",
    main_image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800",
    price_per_person: 350,
    discount_price: 299,
    duration: 4,
    difficulty: "easy",
    max_people: 20,
    rating: 4.5,
    review_count: 98,
    is_featured: true,
  },
  {
    id: 6,
    name: "Harar Jugol City Tour",
    slug: "harar-jugol-tour",
    description: "Discover the ancient walled city of Harar, with its 82 mosques and unique hyena feeding ritual.",
    city: "Harar",
    country: "Ethiopia",
    main_image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800",
    price_per_person: 280,
    discount_price: 249,
    duration: 3,
    difficulty: "easy",
    max_people: 25,
    rating: 4.4,
    review_count: 73,
    is_featured: false,
  },
];

export const mockCategories = [
  { id: 1, name: "Historical" },
  { id: 2, name: "Adventure" },
  { id: 3, name: "Cultural" },
  { id: 4, name: "Nature" },
  { id: 5, name: "Religious" },
];
